#!/bin/bash
#
#uptime skript
#
x=`uptime -p`				# näitab masina uptimei
kellaaeg=`date +"%T"`			# näitab praegust kellaaega
echo -n `hostname`			# väljastab hostnamei
echo -n " at " $kellaaeg $x		# väljastab praegusel kellaajal kaua masin on töödanud
echo
#
#lõpp
#
