#!/bin/bash
#
#uptime skript
#
x=`uptime -p`				# näitab masina uptimei
kellaaeg=`date +"%T"`			# näitab praegust kellaaega
echo "skriptimine at" $kellaaeg $x	# väljastab praegusel kellaajal kaua masin on töödanud
#
#lõpp
#
